# Frontend/Dockerfile.dev
FROM node:20

WORKDIR /app

# Copiar package.json y package-lock.json (si existe)
COPY package*.json ./

# Instalar TODAS las dependencias incluyendo devDependencies
RUN npm install --include=dev

# Copiar el resto de la aplicación
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]